### ISSUE TITLE
no-unlocalized-strings ignoreFunction not working properly

### ISSUE THREAD

**Issue by ythomop** [lingui/eslint-plugin#18]
<img width="1306" alt="image" src="https://github.com/lingui/eslint-plugin/assets/35526357/c7034849-8d3a-4bf4-8e59-ba1e2d5bfcd2">

As you can see, `formatDate` is in the ignoreFunction list, but it's not being ignored. (Running the eslint cli yields the same result, it's not just the IDE)

eslint version: `^8.50.0`
eslint-plugin-lingui: `^0.1.1`

**Comment by andrii-bodnar** [comment]
@ythomop this should be fixed in the [0.1.2](https://github.com/lingui/eslint-plugin/releases/tag/0.1.2) release.
