### ISSUE TITLE
Support Chinese Please

### ISSUE THREAD

**Issue by Sioncovy** [lingui/eslint-plugin#28]
When I use this plugin, it do not work for Chinese, just only check English, number, symbol ...
Could support it check Chinese character? Thanks

<img width="1726" alt="image" src="https://github.com/lingui/eslint-plugin/assets/74760542/bf83f170-52f7-499d-899b-8bbabec43da7">

**Comment by thekip** [comment]
I beleive it's because chinese characters doesn't match this regexp

```js
/^[^A-Za-z]+$/, // ignore not-word string
```
