### ISSUE TITLE
Confusing results of `lingui/no-unlocalized-strings`

### ISSUE THREAD

**Issue by mustafashabib** [lingui/eslint-plugin#30]
Hi there

I am seeing a bit of unexpected behavior and not sure if it's something in my configuration or a misunderstanding on my part. My expectation would be that these would all be flagged by the linter, but it isn't what I'm seeing. 

To reproduce, set the configuration for the `lingui/no-unlocalized-strings` rule to `error` and lint this example function:

```typescript
export const example = ()  => {
    const noLinterError = 'EEEE';
    const secondNoLinterError = "'Tomorrow'";
    const linterError = "'Linter' gets marked as an error";
    const secondLinterError = 'Tomorrow';

    console.log(noLinterError, linterError, secondNoLinterError, secondLinterError);
};
```

I'm confused why the first variable, `noLinterError` and `secondNoLinterError` are not linted as an error, but `linterError` and `secondLinterError` are, which is what I would expect for all four of them. It seems to do with the pattern within the string, and whether it's a single word or repeating characters, and whether the single word is quoted or not.

I'm on the 0.2.2 release of the plugin.

Thanks!

**Comment by thekip** [comment]
I think it's related to the pattern on the https://github.com/lingui/eslint-plugin/blob/main/src/rules/no-unlocalized-strings.ts#L76 line as well as on the line 87. We can ask original author @igorDolzh what was the original idea behind it.

**Comment by mustafashabib** [comment]
Thanks, and thanks for the work on this @igorDolzh  -- any thoughts on why it behaves this way and whether you think it ought to change?

**Comment by timofei-iatsenko** [comment]
close in favour of https://github.com/lingui/eslint-plugin/issues/50
