### ISSUE TITLE
Flat config support (ESLint 9)

### ISSUE THREAD

**Issue by yuriy-yarosh** [lingui/eslint-plugin#31]
Using this plugin with flat config is a bit cumbersome atm.
It would've been nice to update it to the most recent plugin structure and provide couple flat config examples.

**Comment by thekip** [comment]
Could you elaborate a bit on that? May be show some examples by what you mean "cumbersome". As far as i understand having "flat" config vs legacy should not affect plugins and rules only the way how you declare them.

**Comment by yuriy-yarosh** [comment]
> should not affect plugins

It does require very [specific structure](should not affect plugins).

> Could you elaborate a bit on that?

This won't work

```js
import lingui from 'eslint-plugin-lingui';

export default [{
  files: ['*.js', '*.cjs', '**/src/**/*.js', '**/src/**/*.jsx'],
  plugins: {
    lingui,
  },
  rules: {
    ...lingui.configs.recommended.rules
  }
}];
```

This won't work either...

```js
import lingui from 'eslint-plugin-lingui';

export default [{
  files: ['*.js', '*.cjs', '**/src/**/*.js', '**/src/**/*.jsx'],
  plugins: {
    lingui,
  },
  rules: {
    ...Object.fromEntries(Object.entries(lingui.rules).map(([key, value]) => [`lingui/${key}`, 'warn']))
  }
}];
```

Because lingui plugin only exports obsolete rules format, and there are no Configs

![зображення](https://github.com/lingui/eslint-plugin/assets/6811933/695821c7-8c7a-43aa-aa92-cfcee099d96e)

**Comment by thekip** [comment]
Go this, thanks. Would you be interesting opening a PR? It seems it's not a complicated change.

**Comment by yuriy-yarosh** [comment]
@thekip sure, I'll fix this when I'll get some free time.

**Comment by thekip** [comment]
Update: i've just checked the plugin, and it seems it's not a subject for the change at least for now. Because it doesn't expose any "recommended" setup, only rules which are not have to be updated.

**Comment by lemueldizon** [comment]
Waiting on this too. Though I've got a workaround working using [Eslint's compatibility library](https://www.npmjs.com/package/@eslint/compat). Let me know if this workaround works with you all as well.

```js
import { fixupPluginRules } from '@eslint/compat'
import lingui from 'eslint-plugin-lingui'

export default [
  ...
  {
    files: ['**/*.{ts,tsx}'],
    plugins: {
      lingui: fixupPluginRules(lingui)
    },
    rules: {
      'lingui/no-unlocalized-strings': 'error',
      'lingui/t-call-in-function': 'error',
      'lingui/no-single-variables-to-translate': 'error',
      'lingui/no-expression-in-message': 'error',
      'lingui/no-single-tag-to-translate': 'error',
      'lingui/no-trans-inside-trans': 'error'
    }
  },
  ...
]
```

![Screenshot 2024-07-01 080635](https://github.com/lingui/eslint-plugin/assets/23368759/473503e9-32c3-4549-84ac-16a1e6913988)
![Screenshot 2024-07-01 080651](https://github.com/lingui/eslint-plugin/assets/23368759/852e91f0-b3a3-4d74-9106-b197ca7149fe)
