### ISSUE TITLE
no-expression-in-message for Trans tags

### ISSUE THREAD

**Issue by hugohutri** [lingui/eslint-plugin#35]
When using the rule "no-expression-in-message", I would like to have warnings for `<Trans>` tags just like they warn when using `t`

![image](https://github.com/lingui/eslint-plugin/assets/55588133/71f2c031-8f2e-4963-bd5e-29ec34c50788)

**Comment by judeatmerit** [comment]
+1 to `Trans` tags, and also inside `msg` (and by extension, `defineMessage` function calls)
```ts
  const obj = { value: "the value" };
  const example = msg`Expression to the right ${_obj.value} and to the left.`; // no warning here
```

**Comment by thekip** [comment]
We also want to see that. Contributions are welcome!

**Comment by timofei-iatsenko** [comment]
@hugohutri i created a PR https://github.com/lingui/eslint-plugin/pull/60/files enforcing this in the JSX containers is tricky. I haven't thought through all the possible cases here, so will need community help to test it.

**Comment by timofei-iatsenko** [comment]
> +1 to `Trans` tags, and also inside `msg` (and by extension, `defineMessage` function calls)
> 
> ```ts
>   const obj = { value: "the value" };
>   const example = msg`Expression to the right ${_obj.value} and to the left.`; // no warning here
> ```

implemented in https://github.com/lingui/eslint-plugin/pull/61
