### ISSUE TITLE
how to ignore property by pattern?

### ISSUE THREAD

**Issue by KutnerUri** [lingui/eslint-plugin#40]
I'm using lingui/no-unlocalized-strings and it's showing warnings about attributes that shouldn't be localized, for example:

```
// getting error disallow literal stringeslint(lingui/no-unlocalized-strings)
<button data-custom-property-three="some data"/>
```

usually I would solve it with `ignoreAttribute`, but I have a lot of these custom properties. what I would like is to ignore by regex like `data-custom-property-.*`, or a similar syntax.

How can I achieve this?

**Comment by timofei-iatsenko** [comment]
close in favour of https://github.com/lingui/eslint-plugin/issues/50

**Comment by timofei-iatsenko** [comment]
Would be added by this PR: https://github.com/lingui/eslint-plugin/pull/70/files
