### ISSUE TITLE
relaxing dependency version of @typescript-eslint/utils

### ISSUE THREAD

**Issue by braineo** [lingui/eslint-plugin#42]
as of 2024-05-28, the version of 

[@typescript-eslint/utils](https://www.npmjs.com/package/@typescript-eslint/utils) is 7.11 already, installing `eslint-plugin-lingui` in the project with the latest eslint library creates nested dependencies because it require specifically `^5.61.0`

if the plugin does not depend on behavior specifically in version 5, can we relax the version to be `5 || 6 || 7`?

**Comment by thekip** [comment]
Could you try it and make a PR?

**Comment by braineo** [comment]
yup, no problem.  i tested it locally with some of my projects by 


```bash
# inside the repo
npm build
npm pack

# inside the project
npm install path-to-package.tgz
```


 let me know if there are other test i can try
