### ISSUE TITLE
[no-expression-in-message] is not in the recommended rules, despite being documented as such

### ISSUE THREAD

**Issue by jgarplind** [lingui/eslint-plugin#71]
Basically the title.

Obviously not too difficult to enable the rule manually, but I was a bit surprised.

Would be happy to submit a PR if you let me know the direction you prefer:
- Put it in the recommended rules, or
- Remove the ✅ from the README

**Comment by timofei-iatsenko** [comment]
😱 was in harry doing so. Nice catch.  Need to add to the recommended set.
