### ISSUE TITLE
0.8.0: Invalid configuration for no-unlocalized-strings (should NOT have additional properties)

### ISSUE THREAD

**Issue by ptmkenny** [lingui/eslint-plugin#85]
I just updated to 0.8.0 from 0.7. In `.eslintrc.yml`, I removed my original config for `lingui/no-unlocalized-strings` and I replaced it with the suggested starter configuration in the docs.

However, when I check with eslint, it immediately fails:

```
Error: .eslintrc.yml:
	Configuration for rule "lingui/no-unlocalized-strings" is invalid:
	Value {"useTsTypes":true,"ignore":["^(?![A-Z].*|\\w+\\s\\w+).+$","^[A-Z0-9_-]+$"],"ignoreNames":[{"regex":{"pattern":"className","flags":"i"}},{"regex":{"pattern":"^[A-Z0-9_-]+$"}},"styleName","src","srcSet","type","id","width","height","displayName","Authorization"],"ignoreFunctions":["dumpDebugInfo","this.dumpDebugInfo","cva","cn","track","Error","console.*","*headers.set","*.addEventListener","*.removeEventListener","*.postMessage","*.getElementById","*.dispatch","*.commit","*.includes","*.indexOf","*.endsWith","*.startsWith","require"],"ignoreMethodsOnType":["Map.get","Map.has","Set.has"]} should NOT have additional properties.
```

The problem seems to be `ignoreMethodsType`; when I remove that and `Map.get`, `Map.has`, and `Set.has`, then the eslint check runs fine.

**Comment by timofei-iatsenko** [comment]
Thanks for the info. It should be `ignoreMethodsOnTypes` (with `S` at the end) i fixed it there https://github.com/lingui/eslint-plugin/pull/84
