### ISSUE TITLE
Did `ignoreFunction` change name to `ignoreFunctions`?

### ISSUE THREAD

**Issue by jgarplind** [lingui/eslint-plugin#86]
I ran into some issues when using 0.8.0:

> Unexpected property "ignoreFunction". Expected properties: "ignore", "ignoreNames", "ignoreFunctions", "ignoreMethodsOnTypes", "useTsTypes".

Checking the release notes, I saw no mention of this.

However, a codebase search leads me to think that there has been a change? https://github.com/search?q=repo%3Alingui%2Feslint-plugin%20ignoreFunction&type=code

For now I'll just change to `ignoreFunctions`, but it was a bit confusing not to find it in the changelog.

**Comment by timofei-iatsenko** [comment]
fixed here https://github.com/lingui/eslint-plugin/pull/84
