### ISSUE TITLE
Documented 0.8.0 `no-unlocalized-strings` starting point does not seem to match output from 0.7.0

### ISSUE THREAD

**Issue by jgarplind** [lingui/eslint-plugin#88]
Under some circumstances, the config specified here: https://github.com/lingui/eslint-plugin/blob/00bfc7cc5a14db44d8bdf87c17f109ad03a11c69/docs/rules/no-unlocalized-strings.md leads to lint failures where 0.7.0 defaults lead to success.

I think that the 0.7.0 version mostly did a better job. Here are some examples:
1. const url = \`${path}${queryParameters}`, obviously there is nothing to translate here
2. userId: \`${user.id}`, arguably should just be refactored to user.id, but still there is nothing to translate here
3. \<h3>Some actual text\</h3>, an improvement, since 0.7.0 missed this
4. \`${i18n.date(start, { timeStyle: "short" })}${binding}${i18n.date(end, { timeStyle: "short" })}`, a bit more complex, but still, nothing to translate here

Do you have suggestions on how to achieve expected ignores for 1/2/4?

**Comment by timofei-iatsenko** [comment]
It's known issue i prepared a fix for that here https://github.com/lingui/eslint-plugin/pull/84
