### ISSUE TITLE
Is the `lingui/t-call-in-function` rule still relevant?

### ISSUE THREAD

**Issue by gbedardsiceupgrade** [lingui/eslint-plugin#89]
With the v5 release and the usage of `@lingui/core/macro` instead of `@lingui/macro`, the docs don't mention that we should not be using the `t` macro at the module level anymore, as can be seen here:

https://lingui.dev/tutorials/javascript#localizing-your-app

![Screenshot 2024-11-29 at 11 33 51 AM](https://github.com/user-attachments/assets/bef3b39f-b964-4d99-b6b6-a625e6ee7298)

Is the `lingui/t-call-in-function` still relevant, or should it marked as deprecated and removed from the recommended config?

**Comment by gbedardsiceupgrade** [comment]
Looking into it a bit more, it looks like this rule is still relevant? If that's the case, I'm not sure why the disclaimers about not using the `t` macro at the module level have been removed 🤔.

**Comment by timofei-iatsenko** [comment]
Yes, the rule is still relevant. I think that page is completely new, and there was no this disclaimer. 

 @andrii-bodnar could you add this disclaimer into that page?  Also, the examples are written in the way where everything in the module level. This is done to omit all unneccessary details, but this could be misleading for some people.

**Comment by gbedardsiceupgrade** [comment]
Got it, thanks for the clarification. Will close this one then!
